import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Nav } from "@/components/nav/Nav";
import { Footer } from "@/components/footer/Footer";
import { AppChrome } from "@/components/chrome/AppChrome";
import { Breadcrumb } from "@/components/breadcrumb/Breadcrumb";
import { PodcastPlayer } from "@/components/podcast-player/PodcastPlayer";
import podcastsIndex from "@/scripts/podcasts/podcasts-index.json";
import weeklyIndex from "@/scripts/podcasts/weekly-index.json";

interface Backlink { href: string; label: string }
interface Episode {
  slug: string;
  title: string;
  summary: string;
  cast: string[];
  duration: string;
  src: string;
  /** 1:1 painted group-portrait of the cast. Generated by
   *  scripts/generate-podcast-portraits.py --comps. */
  image?: string;
  backlink?: Backlink;
  /** Optional ISO date — Weekly episodes carry one; article companions don't. */
  date?: string;
  /** Internal grouping for display. */
  group: "weekly" | "articles" | "specials";
}

const TITLE = "Podcasts";
const DESCRIPTION =
  "Every podcast on rutgertuit.nl — the recurring weekly conversation about public Google / AI news, one companion episode per long-form article, and the off-format specials. All voices are synthetic; personal views, not Google's.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  openGraph: { title: TITLE, description: DESCRIPTION, type: "website" },
  robots: { index: true, follow: true },
};

// Merge the two registries into one typed list.
const weekly: Episode[] = (weeklyIndex.episodes as Array<Omit<Episode, "group">>).map((e) => ({
  ...e,
  group: "weekly",
}));
const others: Episode[] = (podcastsIndex.episodes as Array<Omit<Episode, "group"> & { group: "articles" | "specials" }>);

const groupsMeta = podcastsIndex.groups as Array<{ id: "articles" | "specials"; name: string; blurb: string }>;
const groupBlurb = (id: Episode["group"]): string => {
  if (id === "weekly") return weeklyIndex.series.description;
  return groupsMeta.find((g) => g.id === id)?.blurb ?? "";
};
const groupName = (id: Episode["group"]): string => {
  if (id === "weekly") return "Weekly";
  return groupsMeta.find((g) => g.id === id)?.name ?? id;
};

const all: Episode[] = [...weekly, ...others];

// The recurring cast. Rutger is the only real person (real portrait, voiced by
// a clone of his own voice); the guests are invented characters with synthetic
// voices and AI-painted portraits.
interface CastMember { name: string; role: string; bio: string; img: string }
const CAST: CastMember[] = [
  {
    name: "Rutger", role: "Host", img: "/assets/portraits/01-studio.png",
    bio: "The host — a technical creative who works where high-performance technology meets human creativity. The one real person here, voiced by a clone of his own voice.",
  },
  {
    name: "Frits", role: "The Nestor", img: "/podcasts/cast/frits.png",
    bio: "A Dutch creative director in his late sixties — weary, brilliant, quotes Mad Men in Dutch. The skeptic who pushes back on the title, then agrees with the article anyway.",
  },
  {
    name: "Dino", role: "The Creative Dinosaur", img: "/podcasts/cast/dino.png",
    bio: "A senior art director who has done the same concept for thirty years and refuses to learn what a hashtag is. Gloriously grumpy — and, annoyingly, usually right.",
  },
  {
    name: "Oracle", role: "The Strategist", img: "/podcasts/cast/oracle.png",
    bio: "A brand strategist who draws Venn diagrams nobody understands and quotes Heidegger during pitches. Serenely certain; has a deck for everything.",
  },
  {
    name: "Angela", role: "The Chief of Staff", img: "/podcasts/cast/angela.png",
    bio: "Unflappable, procedural, dry, German. Loves clear documentation. Her deadpan is the whole joke.",
  },
  {
    name: "Marie", role: "The Compliance Researcher", img: "/podcasts/cast/marie.png",
    bio: "Keeps everyone definitionally honest, in short precise interjections. Never a word wasted.",
  },
  {
    name: "Saar", role: "The Actress", img: "/podcasts/cast/saar.png",
    bio: "A famous Dutch actress with a gorgeous, raspy voice and no idea what anyone is talking about. Asks the wrong question — beautifully.",
  },
];

// PodcastSeries JSON-LD — one umbrella series covering the whole corpus.
const ld = {
  "@context": "https://schema.org",
  "@type": "PodcastSeries",
  "@id": "https://rutgertuit.nl/podcasts#series",
  name: "rutgertuit.nl podcasts",
  description: DESCRIPTION,
  url: "https://rutgertuit.nl/podcasts",
  inLanguage: "en",
  author: { "@id": "https://rutgertuit.nl/#person" },
  episode: all.map((ep) => ({
    "@type": "PodcastEpisode",
    name: ep.title,
    description: ep.summary,
    url: `https://rutgertuit.nl/podcasts#${ep.slug}`,
    ...(ep.date ? { datePublished: ep.date } : {}),
    associatedMedia: {
      "@type": "MediaObject",
      contentUrl: `https://rutgertuit.nl${ep.src}`,
      encodingFormat: "audio/mpeg",
    },
  })),
};

export default function PodcastsPage() {
  const order: Episode["group"][] = ["weekly", "articles", "specials"];
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(ld) }}
      />
      <Nav />
      <Breadcrumb trail={[
        { label: "Home", href: "/" },
        { label: "Podcasts" },
      ]} />
      <article className="rt-tuit section section--surface">
        <div className="container">
          <div className="rt-tuit__head">
            <div className="eyebrow eyebrow--warm">PODCASTS · SYNTHETIC AI VOICES</div>
            <h1 className="rt-tuit__title">Every podcast on this site.</h1>
            <p className="rt-tuit__lead">
              {DESCRIPTION} Each episode is reachable in context on the page it was made
              for; this is the umbrella view. Personal views, not Google&apos;s. The
              site-wide disclaimer in the footer governs every episode.
            </p>
          </div>

          {order.map((groupId) => {
            const items = all.filter((e) => e.group === groupId);
            if (items.length === 0) return null;
            return (
              <section
                key={groupId}
                id={groupId}
                aria-labelledby={`${groupId}-title`}
                style={{ marginTop: "var(--space-7)" }}
              >
                <div className="eyebrow" style={{ marginBottom: "var(--space-2)" }}>
                  {groupName(groupId).toUpperCase()}
                </div>
                <h2 id={`${groupId}-title`} className="rt-tuit__stage-label" style={{ marginBottom: "var(--space-3)" }}>
                  {groupBlurb(groupId)}
                </h2>
                <ul style={{ listStyle: "none", padding: 0, margin: 0 }}>
                  {items.map((ep) => (
                    <li
                      key={ep.slug}
                      id={ep.slug}
                      style={{
                        display: "grid",
                        gridTemplateColumns: "minmax(0, 240px) 1fr",
                        gap: "var(--space-5)",
                        alignItems: "start",
                        marginBottom: "var(--space-6)",
                      }}
                      className="rt-podcast-row"
                    >
                      {ep.image ? (
                        <Image
                          src={ep.image}
                          alt={`Painted group portrait of the cast: ${ep.cast.join(", ")}`}
                          width={1024}
                          height={1024}
                          sizes="(max-width: 720px) 100vw, 240px"
                          style={{
                            width: "100%",
                            height: "auto",
                            borderRadius: "var(--radius-md)",
                            display: "block",
                          }}
                        />
                      ) : (
                        <div aria-hidden="true" />
                      )}
                      <div>
                        <div className="eyebrow" style={{ marginBottom: "var(--space-2)" }}>
                          {ep.date ? formatDate(ep.date) + " · " : ""}
                          {ep.cast.join(" · ")}
                        </div>
                        <h3 style={{ margin: "0 0 var(--space-2)" }}>{ep.title}</h3>
                        <p style={{ margin: "0 0 var(--space-3)" }}>{ep.summary}</p>
                        <PodcastPlayer
                          src={ep.src}
                          title={ep.title}
                          eyebrow={`${ep.duration} · ${ep.cast.join(" · ")} · SYNTHETIC AI VOICES`}
                          duration={ep.duration}
                        />
                        {ep.backlink && (
                          <p style={{ marginTop: "var(--space-3)", fontSize: "var(--fs-50)", color: "var(--color-fg-3)" }}>
                            On this site: <Link href={ep.backlink.href}>{ep.backlink.label}</Link>.
                          </p>
                        )}
                      </div>
                    </li>
                  ))}
                </ul>
              </section>
            );
          })}

          <section id="cast" aria-labelledby="cast-title" style={{ marginTop: "var(--space-7)" }}>
            <div className="eyebrow" style={{ marginBottom: "var(--space-2)" }}>THE CAST</div>
            <h2 id="cast-title" className="rt-tuit__stage-label" style={{ marginBottom: "var(--space-3)" }}>
              Who you&apos;re listening to.
            </h2>
            <p style={{ margin: "0 0 var(--space-5)", maxWidth: "68ch" }}>
              Rutger is the only real person — voiced by a clone of his own voice. Everyone
              else is an invented character with a synthetic voice, and the painted portraits
              are AI-generated, like everything on this site.
            </p>
            <ul
              style={{
                listStyle: "none",
                padding: 0,
                margin: 0,
                display: "grid",
                gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))",
                gap: "var(--space-5)",
              }}
            >
              {CAST.map((m) => (
                <li key={m.name}>
                  <div
                    style={{
                      position: "relative",
                      aspectRatio: "1 / 1",
                      borderRadius: "var(--radius-md)",
                      overflow: "hidden",
                      marginBottom: "var(--space-3)",
                    }}
                  >
                    <Image
                      src={m.img}
                      alt={`Portrait of ${m.name}`}
                      fill
                      sizes="(max-width: 720px) 50vw, 220px"
                      style={{ objectFit: "cover" }}
                    />
                  </div>
                  <div className="eyebrow" style={{ marginBottom: "var(--space-2)" }}>
                    {m.role.toUpperCase()}
                  </div>
                  <h3 style={{ margin: "0 0 var(--space-2)" }}>{m.name}</h3>
                  <p style={{ margin: 0, fontSize: "var(--fs-100)", color: "var(--color-fg-2)" }}>
                    {m.bio}
                  </p>
                </li>
              ))}
            </ul>
          </section>
        </div>
      </article>
      <Footer />
      <AppChrome />
    </>
  );
}

function formatDate(iso: string): string {
  const d = new Date(iso + "T00:00:00Z");
  return d.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric", timeZone: "UTC" });
}
